# These are supported funding model platforms

github:[SeeChen]
patreon:SeeChen
open_collective:SeeChen
ko_fi:SeeChen
tidelift:aaa/bbb
community_bridge:java-lang
liberapay:
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
